export const workshopData = [
  {
    month: "JUL",
    day: "12",
    year: "2025",
    title: "(1A) ALL/ ALL MRD (Day 1)",
    status: "Open",
    bgColor: "extra_light",
    statusColor: "text-[#4AB518]",
  },
  {
    month: "JUL",
    day: "22",
    year: "2025",
    title: "(1B) AML/ AML MRD (Day 2)",
    status: "Close",
    bgColor: "light-green",
    statusColor: "text-[#F96062]",
  },
  {
    month: "JUL",
    day: "12",
    year: "2025",
    title: "(2) FCM in CMML/ MPN/ MDS",
    status: "Open",
    bgColor: "light_yellow_color",
    statusColor: "text-[#4AB518]",
  },
  {
    month: "JUL",
    day: "29",
    year: "2025",
    title: "(3A) B CLPD",
    status: "Open",
    bgColor: "orange_color",
    statusColor: "text-[#4AB518]",
  },
  {
    month: "JUL",
    day: "29",
    year: "2025",
    title: "(3B) T CLPD",
    status: "Close",
    bgColor: "light_blue",
    statusColor: "text-[#F96062]",
  },
  {
    month: "JUL",
    day: "29",
    year: "2025",
    title: "(4) Spectral Flow Cytometry",
    status: "Open",
    bgColor: "bg-[#F8E3FB]",
    statusColor: "text-[#4AB518]",
  },

  {
    month: "JUL",
    day: "12",
    year: "2025",
    title: "(6) High Dimensional Data Driven Discovery",
    status: "Open",
    bgColor: "extra_light",
    statusColor: "text-[#4AB518]",
  },
  {
    month: "JUL",
    day: "22",
    year: "2025",
    title: "(7) Image Enabled Sorting",
    status: "Close",
    bgColor: "light-green",
    statusColor: "text-[#F96062]",
  },
  {
    month: "JUL",
    day: "12",
    year: "2025",
    title: "(8) Inborn errors of Immunity",
    status: "Open",
    bgColor: "light_yellow_color",
    statusColor: "text-[#4AB518]",
  },
  {
    month: "JUL",
    day: "29",
    year: "2025",
    title: "(9) FCM in Non-Hematological Neoplasms",
    status: "Open",
    bgColor: "orange_color",
    statusColor: "text-[#4AB518]",
  },
  {
    month: "JUL",
    day: "29",
    year: "2025",
    title: "(10) CBA for Cytokines",
    status: "Close",
    bgColor: "light_blue",
    statusColor: "text-[#F96062]",
  },
];
