export const ConfernceCardData = [
  {
    month: "JUL",
    day: "12",
    year: "2025",
    title: "Travel Awards Guidelines",
    status: "Open",
    bgColor: "extra_light",
    statusColor: "text-[#4AB518]",
  },
  {
    month: "JUL",
    day: "22",
    year: "2025",
    title: "Oral paper/ Poster awards",
    status: "Close",
    bgColor: "light-green",
    statusColor: "text-[#F96062]",
  },
  {
    month: "JUL",
    day: "12",
    year: "2025",
    title: "Oral Presentation Guidelines",
    status: "Open",
    bgColor: "light_yellow_color",
    statusColor: "text-[#4AB518]",
  },
  {
    month: "JUL",
    day: "29",
    year: "2025",
    title: "Abstract Submission Guidelines",
    status: "Open",
    bgColor: "orange_color",
    statusColor: "text-[#4AB518]",
  },
  {
    month: "JUL",
    day: "29",
    year: "2025",
    title: "Oral paper/ Poster awards",
    status: "Close",
    bgColor: "light_blue",
    statusColor: "text-[#F96062]",
  },
  {
    month: "JUL",
    day: "29",
    year: "2025",
    title: "PPT Templet For Oral Presentation",
    status: "Open",
    bgColor: "bg-[#F8E3FB]",
    statusColor: "text-[#4AB518]",
  },

  //   dubicates entery

  {
    month: "JUL",
    day: "12",
    year: "2025",
    title: "Travel Awards Guidelines",
    status: "Open",
    bgColor: "extra_light",
    statusColor: "text-[#4AB518]",
  },
  {
    month: "JUL",
    day: "22",
    year: "2025",
    title: "Oral paper/ Poster awards",
    status: "Close",
    bgColor: "light-green",
    statusColor: "text-[#F96062]",
  },
  {
    month: "JUL",
    day: "12",
    year: "2025",
    title: "Oral Presentation Guidelines",
    status: "Open",
    bgColor: "light_yellow_color",
    statusColor: "text-[#4AB518]",
  },
  {
    month: "JUL",
    day: "29",
    year: "2025",
    title: "Abstract Submission Guidelines",
    status: "Open",
    bgColor: "orange_color",
    statusColor: "text-[#4AB518]",
  },
  {
    month: "JUL",
    day: "29",
    year: "2025",
    title: "Oral paper/ Poster awards",
    status: "Close",
    bgColor: "light_blue",
    statusColor: "text-[#F96062]",
  },
  {
    month: "JUL",
    day: "29",
    year: "2025",
    title: "PPT Templet For Oral Presentation",
    status: "Open",
    bgColor: "bg-[#F8E3FB]",
    statusColor: "text-[#4AB518]",
  },
  {
    month: "JUL",
    day: "12",
    year: "2025",
    title: "Travel Awards Guidelines",
    status: "Open",
    bgColor: "extra_light",
    statusColor: "text-[#4AB518]",
  },
  {
    month: "JUL",
    day: "22",
    year: "2025",
    title: "Oral paper/ Poster awards",
    status: "Close",
    bgColor: "light-green",
    statusColor: "text-[#F96062]",
  },
  {
    month: "JUL",
    day: "12",
    year: "2025",
    title: "Oral Presentation Guidelines",
    status: "Open",
    bgColor: "light_yellow_color",
    statusColor: "text-[#4AB518]",
  },
  {
    month: "JUL",
    day: "29",
    year: "2025",
    title: "Abstract Submission Guidelines",
    status: "Open",
    bgColor: "orange_color",
    statusColor: "text-[#4AB518]",
  },
  {
    month: "JUL",
    day: "29",
    year: "2025",
    title: "Oral paper/ Poster awards",
    status: "Close",
    bgColor: "light_blue",
    statusColor: "text-[#F96062]",
  },
  {
    month: "JUL",
    day: "29",
    year: "2025",
    title: "PPT Templet For Oral Presentation",
    status: "Open",
    bgColor: "bg-[#F8E3FB]",
    statusColor: "text-[#4AB518]",
  },
];
